export const navData = [
    {
        id:1,
        name:'Home',
        to:"/",
    },
    {
        id:2,
        name:'Services',
        to:"/Services",
    },
    {
        id:3,
        name:'About',
        to:"/About",
    },
    {
        id:4,
        name:'Contact',
        to:"/Contact",
    },
]